apiVersion: v1
kind: ConfigMap
metadata:
  name: is-skeletons-detector
  namespace: default
data:
  detector: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "models_folder": "/models/",
      "model": "COCO",
      "network_resolution": {
        "width": -1,
        "height": 256
      },
      "output_resolution": {
        "width": -1,
        "height": -1
      },
      "scale_gap": {
        "value": 0.3
      },
      "scale_number": {
        "value": 1
      }
    }

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-detector"
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: detector
    spec:
      nodeSelector:
        min_cuda_version: "8"
      containers:
      - name: "detector"
        image: labviros/is-skeletons-detector:0.0.2-openpose
        args: ["/opt/is/stream.bin", "/opt/options/options.json"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
            nvidia.com/gpu: 1
        volumeMounts:
          - name: options
            mountPath: /opt/options
      terminationGracePeriodSeconds: 1
      volumes:
      - name: options
        configMap:
          name: is-skeletons-detector
          items:
          - key: detector
            path: options.json