apiVersion: v1
kind: ConfigMap
metadata:
  name: is-robot-controller-config
  namespace: default
data:
  config: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_uri": "http://zipkin.default",
      "robot_frame_id": 100,
      "world_frame_id": 1000,
      "parameters": {
        "robot_id": 0,
        "center_offset": 0.2,
        "speed_limits": [
          1.0,
          1.0,
          0.7,
          45.0
        ],
        "gains": [
          0.4,
          0.4
        ],
        "allowed_measurement_disruption": "0.2s"
      }
    }

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-robot-controller"
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: is-robot-controller 
    spec:
      containers:
      - name: service 
        image: labviros/is-robot-controller:0.0.3
        command: ["/service.bin"]
        args: ["/opt/options/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1.0"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /opt/options
      volumes:
      - name: options
        configMap:
          name: is-robot-controller-config
          items:
          - key: config
            path: options.json
