apiVersion: v1
kind: ConfigMap
metadata:
  name: skeletons-grouper
  namespace: default
data:
  grouper_0: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "id": 0,
      "cameras": {
        "0" : {"vertices": [{"x": 0.0, "y": 0.0}, {"x": 0.5, "y": 1.0}]},
        "1": {},
        "2": {},
        "3": {},
        "4": {}
      },
      "referential": 1000,
      "min_error": 30.0,
      "min_score": 0.4,
      "max_distance": 0.85,
      "period_ms": 200,
      "release_samples": 5
    }
  grouper_1: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "id": 1,
      "cameras": {
        "0" : {"vertices": [{"x": 0.5, "y": 0.0}, {"x": 1.0, "y": 1.0}]},
        "2": {},
        "4": {},
        "6": {}
      },
      "referential": 1001,
      "min_error": 30.0,
      "min_score": 0.4,
      "max_distance": 0.85,
      "period_ms": 200,
      "release_samples": 5
    }
  grouper_2: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "id": 2,
      "cameras": {
        "5" : {"vertices": [{"x": 0.1, "y": 0.0}, {"x": 0.75, "y": 1.0}]},
        "6" : {"vertices": [{"x": 0.25, "y": 0.0}, {"x": 0.75, "y": 1.0}]},
        "7": {}
      },
      "referential": 1003,
      "min_error": 30.0,
      "min_score": 0.4,
      "max_distance": 0.85,
      "period_ms": 200,
      "release_samples": 5
    }

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-grouper"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grouper
    spec:
      containers:
      - name: "0"
        image: viros/is-skeletons-grouper:0.0.2
        command: ["./service.bin"]
        args: ["/conf/options_0.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /conf/
      - name: "1"
        image: viros/is-skeletons-grouper:0.0.2
        command: ["./service.bin"]
        args: ["/conf/options_1.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /conf/
      - name: "2"
        image: viros/is-skeletons-grouper:0.0.2
        command: ["./service.bin"]
        args: ["/conf/options_2.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /conf/
      volumes:
      - name: options
        configMap:
          name: skeletons-grouper
          items:
          - key: grouper_0
            path: options_0.json
          - key: grouper_1
            path: options_1.json
          - key: grouper_2
            path: options_2.json
